export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE'
}

export const userConstants = {
    USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE : 'USER_REGISTER_FAILURE'
}


export const postConstants = {
    POST_REGISTER_REQUEST : 'POST_REGISTER_REQUEST',
    POST_REGISTER_SUCCESS : 'POST_REGISTER_SUCCESS',
    POST_REGISTER_FAILURE : 'POST_REGISTER_FAILURE'
}

export const allPostsConstants = {
    ALL_POSTS_REQUEST : 'ALL_POSTS_REQUEST',
    ALL_POSTS_SUCCESS : 'ALL_POSTS_SUCCESS',
    ALL_POSTS_FAILURE : 'ALL_POSTS_SUCCESS'
}

export const postClickedConstants = {
    POST_CLICKED_REQUEST : 'POST_CLICKED_REQUEST',
    POST_CLICKED_SUCCESS : 'POST_CLICKED_SUCCESS',
    POST_CLICKED_FAILURE : 'POST_CLICKED_FAILURE'
}


export const bicycleConstants = {
    BICYCLE_CREATE_REQUEST : 'BICYCLE_CREATE_REQUEST',
    BICYCLE_CREATE_SUCCESS : 'BICYCLE_CREATE_SUCCESS',
    BICYCLE_CREATE_FAILURE : 'BICYCLE_CREATE_FAILURE'
}

export const allBicycleConstants = {
    ALL_BICYCLE_REQUEST : 'ALL_BICYCLE_REQUEST',
    ALL_BICYCLE_SUCCESS : 'ALL_BICYCLE_SUCCESS',
    ALL_BICYCLE_FAILURE : 'ALL_BICYCLE_FAILURE'
}

export const requestBicycleConstants = {
    REQUEST_BICYCLE_REQUEST : 'REQUEST_BICYCLE_REQUEST',
    REQUEST_BICYCLE_SUCCESS : 'REQUEST_BICYCLE_SUCCESS',
    REQUEST_BICYCLE_FAILURE : 'REQUEST_BICYCLE_FAILURE'
}

export const allRequestConstants = {
    ALL_REQUEST_REQUEST : 'ALL_REQUEST_REQUEST',
    ALL_REQUEST_SUCCESS : 'ALL_REQUEST_SUCCESS',
    ALL_REQUEST_FAILURE : 'ALL_REQUEST_FAILURE'
}

export const acceptRequestConstants = {
    ACCEPT_REQUEST_REQUEST : 'ACCEPT_REQUEST_REQUEST',
    ACCEPT_REQUEST_SUCCESS : 'ACCEPT_REQUEST_SUCCESS',
    ACCEPT_REQUEST_FAILURE : 'ACCEPT_REQUEST_FAILURE'
}


export const declineRequestConstants = {
    DECLINE_REQUEST_REQUEST : 'DECLINE_REQUEST_REQUEST',
    DECLINE_REQUEST_SUCCESS : 'DECLINE_REQUEST_SUCCESS',
    DECLINE_REQUEST_FAILURE : 'DECLINE_REQUEST_FAILURE'
}

export const allMyBicycleConstants = {
    ALL_MY_BICYCLE_REQUEST : 'ALL_MY_BICYCLE_REQUEST',
    ALL_MY_BICYCLE_SUCCESS : 'ALL_MY_BICYCLE_SUCCESS',
    ALL_MY_BICYCLE_FAILURE : 'ALL_MY_BICYCLE_FAILURE'
}

export const bicycleReturnRequestConstants = {
    BICYCLE_RETURN_REQUEST_REQUEST : 'BICYCLE_RETURN_REQUEST_REQUEST',
    BICYCLE_RETURN_REQUEST_SUCCESS : 'BICYCLE_RETURN_REQUEST_SUCCESS',
    BICYCLE_RETURN_REQUEST_FAILURE : 'BICYCLE_RETURN_REQUEST_FAILURE'
}

export const allReturnRequestConstants = {
    ALL_RETURN_REQUEST_REQUEST : 'ALL_RETURN_REQUEST_REQUEST',
    ALL_RETURN_REQUEST_SUCCESS : 'ALL_RETURN_REQUEST_SUCCESS',
    ALL_RETURN_REQUEST_FAILURE : 'ALL_RETURN_REQUEST_FAILURE'
}


export const acceptReturnRequestConstants = {
    ACCEPT_RETURN_REQUEST_REQUEST : 'ACCEPT_RETURN_REQUEST_REQUEST',
    ACCEPT_RETURN_REQUEST_SUCCESS : 'ACCEPT_RETURN_REQUEST_SUCCESS',
    ACCEPT_RETURN_REQUEST_FAILURE : 'ACCEPT_RETURN_REQUEST_FAILURE'
}


export const declineReturnRequestConstants = {
    DECLINE_RETURN_REQUEST_REQUEST : 'DECLINE_RETURN_REQUEST_REQUEST',
    DECLINE_RETURN_REQUEST_SUCCESS : 'DECLINE_RETURN_REQUEST_SUCCESS',
    DECLINE_RETURN_REQUEST_FAILURE : 'DECLINE_RETURN_REQUEST_FAILURE'
}


export const allRequestedBicycleConstants = {
    ALL_REQUESTED_BICYCLE_REQUEST : 'ALL_REQUESTED_BICYCLE_REQUEST',
    ALL_REQUESTED_BICYCLE_SUCCESS : 'ALL_REQUESTED_BICYCLE_SUCCESS',
    ALL_REQUESTED_BICYCLE_FAILURE : 'ALL_REQUESTED_BICYCLE_FAILURE'
}